Language = 'Go'
Cmd = './main'
Args = []
Reactive = false
TesterPath = 'tools/target/release/tester'
VisPath = 'tools/target/release/vis'
GenPath = 'tools/target/release/gen'
InfilePath = 'tools/in/'
OutfilePath = './out'
Jobs = 4
Cloud = false
CloudURL = ''
CompilerURL = 'https://go-compiler-xjfyzk4rjq-an.a.run.app/compiler'
Source = 'main.go'
CompileCmd = 'go build -o main main.go'
Binary = 'main'
Bucket = 'ahc027-binary'
WorkerURL = 'https://worker-xjfyzk4rjq-an.a.run.app/worker'
ConcurrentRequests = 500
TimeLimitMS = 100000